version: '3'

services:
  reviews:
    build:
      context: .
    image: chrisw321/improvedserver
    depends_on:
      - database
    ports:
      - '3025:3025'

  database:
    build: ./database
    ports:
      - '3306:3306'